config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'projects#index'

  namespace :webhooks do
    post '/github', to: 'github#create'
  end

  resources :projects do
    member do
      get :settings
      get :compare
    end
    resources :test_runs, only: :create
    resources :test_cases, only: :show
  end
end

app/models/project.rb
class Project < ApplicationRecord
  before_validation :set_uid, on: :create

  validates :name, presence: true, uniqueness: true
  validates :uid, presence: true, uniqueness: true

  has_many :test_runs, dependent: :destroy
  has_many :test_cases, through: :test_runs

  def last_test_run
    test_runs.order("timestamp ASC").last
  end

  # Maybe we just save the repo as a field, along with the github installation
  # id. This is fine for now :o)
  def repo
    github_url.split("github.com/").second
  end

  def organisation
    repo.split("/").first
  end

  private

  def set_uid
    uid = nil
    loop do
      uid = SecureRandom.urlsafe_base64(9).gsub(/-|_/,('a'..'z').to_a[rand(26)])
      break unless self.class.name.constantize.where(:uid => uid).exists?
    end
    self.uid = uid
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :find_project, except: [:index, :new, :create]

  def index
    @projects = Project.all.order(:created_at).includes(:test_runs)
  end

  def show
    unless @project.test_runs.any?
      render :show and return
    end

    if params[:start_date].present?
      start_date = Date.parse(params[:start_date])
    end

    if params[:end_date].present?
      end_date = Date.parse(params[:end_date])
    end

    @branches = @project.test_runs.distinct.pluck(:branch).sort
    @current_branch = @branches.include?('master') ? 'master' : @branches.first

    if params[:branch].present?
      @current_branch = params[:branch]
    end

    test_runs = @project.test_runs.where(branch: @current_branch)

    if start_date && end_date
      if end_date < start_date
        # Validate start date is before end date and notify user
        flash.now[:alert] = "The start date needs to be before the end date."
      else
        # Find the nearest test runs to the start and end
        @first_run = test_runs.where("timestamp <= ?", start_date).order("timestamp DESC").first
        @last_run = test_runs.where("timestamp >= ?", end_date).order("timestamp ASC").first
      end
    end

    # Otherwise, get the first and last test runs for this project
    ordered_test_runs = test_runs.order("timestamp asc")
    @first_run = @first_run || ordered_test_runs.first
    @last_run = @last_run || ordered_test_runs.last

    @diff = Diff.new(@first_run, @last_run).all(sort_column, sort_direction)
  end

  # Compare two test runs against each other, given their commit shas.
  def compare
    @base = TestRun.find_by(commit: params[:base])
    @compare = TestRun.find_by(commit: params[:compare])

    if @base.nil? || @compare.nil?
      redirect_to project_path(@project), alert: 'Could not find those test runs, sorry!'
      return
    end

    @diff = Diff.new(@base, @compare)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to project_path(@project), notice: 'Project created'
    else
      render :new
    end
  end

  def settings; end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project), notice: 'Project updated'
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_path, notice: 'Project deleted'
    else
      redirect_to projects_path, alert: 'Something went wrong'
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :github_url)
  end

  def find_project
    @project = Project.find params[:id]
  end

  # These are the different column names of the result of a diff
  # The defult value for the sort column is the time_diff
  def sort_column
    %w[name time_diff last_run_time first_run_time].include?(params[:sort]) ? params[:sort] : "time_diff"
  end

  # The defult value for the sort direction is desc
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    .border.border-red-400.rounded.p-4.text-red-600.my-4
      %p.mb-2 Some errors prevented the project from being saved:
      %ul.list-disc.list-inside
        - @project.errors.full_messages.each do |error|
          %li.text-red-600= error

  = f.label :name
  = f.text_field :name, class: 'input'

  = f.label :github_url
  = f.text_field :github_url, class: 'input'

  .text-center.my-5
    = f.submit class: 'button'

app/views/projects/compare.html.haml
.grid.grid-cols-12.my-4
  .col-span-6
    %h1.text-4xl= @project.name
  .col-span-6.text-right
    .my-3
      = link_to 'View project settings', settings_project_path(@project), class: 'link'

- if @diff.all
  %h3.text-lg
    Viewing change between
    = link_to @base.commit, "#{@project.github_url}/commit/#{@base.commit}", class: 'link'
    and 
    = link_to @compare.commit, "#{@project.github_url}/commit/#{@compare.commit}", class: 'link'
  .grid.grid-cols-12.gap-4.my-6
    .col-span-3
      .my-4
        %p Nº tests in base: #{@base.tests}
        %p Nº tests in compare: #{@compare.tests}
        %p Total in common: #{@diff.all.length}

      .my-4
        - if [@project.github_url, @base.commit, @compare.commit].all?(&:present?)
          = link_to 'View code diff between these dates', "#{@project.github_url}/compare/#{@base.commit}..#{@compare.commit}", class: 'link', target: '_blank'
        - else
          = link_to 'Add a link to your GitHub repo to view the code diff', edit_project_path(@project), class: 'link'

    .col-span-9
      .grid.grid-cols-12.gap-4
        .col-span-3
      %table.table-fixed.w-full
        %thead
          %tr
            %th{class: 'md:w-3/5 xl:w-3/5'} Test
            %th First run test time
            %th Last run test time
            %th Change in test run time
        %tbody.border
          - @diff.all.each do |test|
            %tr.border
              %td.text-sm
                %p
                  .italic= test['file']
                  = link_to test['name'], project_test_case_path(@project, test['hash_code']), class: 'link'
              %td.text-center= test['first_run_time']
              %td.text-center= test['last_run_time']
              %td.text-center{class: test['time_diff'].to_f <= 0 ? 'text-green-500' : 'text-red-600'}
                = test['time_diff'].to_f > 0 ? "+#{test['time_diff']}" : test["time_diff"]
- else
  %p No test runs yet! Have you added a step to upload them in your CI?
  %pre.bg-gray-100.p-4.my-6.overflow-x-scroll
    %code
      curl #{root_url}projects/#{@project.uid}/test_runs \
      \
      \-F file=@/tmp/test-results/rspec.xml \
      \-F branch=BRANCH \
      \-F commit=COMMIT

app/views/projects/edit.html.haml
%div{class: 'mx-auto md:w-1/2'}
  %h1.text-2xl.my-4.text-center Editing project: #{@project.name}
  = render 'form'

app/views/projects/index.html.haml
.grid.grid-cols-12.my-4
  .col-span-6
    %h1.text-4xl Your projects
  .col-span-6.text-right
    .my-3
      = link_to 'Add a project', new_project_path, class: 'link'

%section.my-10
  - if @projects.load.any?
    %table.border.table-fixed
      %thead
        %tr.border
          %th
          %th Number of tests
          %th Last test run received
          %th
      %tbody
        - @projects.each do |project|
          %tr.text-center.border
            %th.text-left.text-lg= project.name
            %td= project.last_test_run&.tests
            %td= project.last_test_run ? "#{time_ago_in_words(project.last_test_run.timestamp).capitalize} ago" : ''
            %td= link_to 'View test details', project_path(project), class: 'button'

app/views/projects/new.html.haml
%div{class: 'mx-auto md:w-1/2'}
  %h1.text-2xl.my-4.text-center Create new project
  = render 'form'

app/views/projects/settings.html.haml
.grid.grid-cols-12.my-4
  .col-span-6
    %h1.text-4xl= @project.name
  .col-span-6.text-right
    .my-3
      = link_to 'Back to project overview', project_path(@project), class: 'link'

.my-10
  %table
    %tbody
      %tr
        %th.text-left GitHub URL
        %td
          - if @project.github_url.present?
            %span.link= link_to @project.github_url, @project.github_url
          - else
            %span= link_to 'Add GitHub URL', edit_project_path(@project), class: 'link'

      %tr
        %th.text-left UID
        %td= @project.uid

      %tr
        %td{colspan: 2}
          = link_to 'Edit', edit_project_path(@project), class: 'link mr-2'
          = link_to 'Delete', project_path(@project), class: 'link', method: :delete, data: { confirm: 'Are you sure? This will also delete any associated test runs.' }

app/views/projects/show.html.haml
.grid.grid-cols-12.my-4
  .col-span-6
    %h1.text-4xl= @project.name
  .col-span-6.text-right
    .my-3
      = link_to 'View project settings', settings_project_path(@project), class: 'link'

- if @diff
  %h3.text-lg
    Viewing change between
    %span.font-semibold #{@first_run.timestamp.to_formatted_s(:long)}
    and
    %span.font-semibold #{@last_run.timestamp.to_formatted_s(:long)}
    on branch
    %span.font-semibold #{@current_branch}.
  .grid.grid-cols-12.gap-4.my-6
    .col-span-3
      .my-4
        = form_tag project_path(@project), method: :get do
          .py-2.test-start-date-picker
            = label_tag :start_date, 'Start date', {class: 'block mb-2'}
            = text_field_tag :start_date, @first_run.timestamp, {data: { behavior: 'flatpickr' }, class: 'input test-datepicker'}
          .py-2.test-end-date-picker
            = label_tag :end_date, 'End date', {class: 'block mb-2'}
            = text_field_tag :end_date, @last_run.timestamp, {data: { behavior: 'flatpickr' }, class: 'input test-datepicker'}
          .py-2
            = label_tag :branch, 'Branch', {class: 'block mb-2'}
            = select_tag :branch, options_for_select(@branches, @current_branch), { class: 'input'}

          = submit_tag 'Submit', {class: 'button'}

      .my-4
        %p Nº tests in first run: #{@first_run.tests}
        %p Nº tests in last run: #{@last_run.tests}
        %p Total in common: #{@diff.length}


      .my-4
        - if @project.github_url.present?
          = link_to 'View code diff between these dates', "#{@project.github_url}/compare/#{@first_run.commit}..#{@last_run.commit}", class: 'link', target: '_blank'
        - else
          = link_to 'Add a link to your GitHub repo to view the code diff', edit_project_path(@project), class: 'link'

    .col-span-9
      .grid.grid-cols-12.gap-4
        .col-span-3
      %table.table-fixed.w-full
        %thead
          %tr
            %th{class: 'md:w-3/5 xl:w-3/5'}= sortable 'name', 'Test'
            %th= sortable 'first_run_time', 'First run test time'
            %th= sortable 'last_run_time', 'Last run test time'
            %th= sortable 'time_diff', 'Change in test run time'
        %tbody.border
          - @diff.each do |test|
            %tr.border
              %td.text-sm
                %p
                  .italic= test['file']
                  = link_to test['name'], project_test_case_path(@project, test['hash_code']), class: 'link'
              %td.text-center= test['first_run_time']
              %td.text-center= test['last_run_time']
              %td.text-center{class: test['time_diff'].to_f <= 0 ? 'text-green-500' : 'text-red-600'}
                = test['time_diff'].to_f > 0 ? "+#{test['time_diff']}" : test["time_diff"]
- else
  %p No test runs yet! Have you added a step to upload them in your CI?
  %pre.bg-gray-100.p-4.my-6.overflow-x-scroll
    %code
      curl #{root_url}projects/#{@project.uid}/test_runs \
      \
      \-F file=@/tmp/test-results/rspec.xml \
      \-F branch=BRANCH \
      \-F commit=COMMIT